"""create initial tables

Revision ID: d2f9333db4f1
Revises: 
Create Date: 2026-02-07 10:18:37.952511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f9333db4f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('papers_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_run_id'), 'digests', ['run_id'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('categories', sa.String(length=200), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_papers_run_id'), 'papers', ['run_id'], unique=False)
    op.create_table('paper_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('category_score', sa.Float(), nullable=False),
    sa.Column('llm_interest_score', sa.Float(), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_scores_final_score'), 'paper_scores', ['final_score'], unique=False)
    op.create_index(op.f('ix_paper_scores_paper_id'), 'paper_scores', ['paper_id'], unique=True)
    op.create_index(op.f('ix_paper_scores_rank'), 'paper_scores', ['rank'], unique=False)
    op.create_index(op.f('ix_paper_scores_run_id'), 'paper_scores', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_scores_run_id'), table_name='paper_scores')
    op.drop_index(op.f('ix_paper_scores_rank'), table_name='paper_scores')
    op.drop_index(op.f('ix_paper_scores_paper_id'), table_name='paper_scores')
    op.drop_index(op.f('ix_paper_scores_final_score'), table_name='paper_scores')
    op.drop_table('paper_scores')
    op.drop_index(op.f('ix_papers_run_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_digests_run_id'), table_name='digests')
    op.drop_table('digests')
    op.drop_table('runs')
    # ### end Alembic commands ###
